import type { Gender } from "@/types/product";

/**
 * Fictitious demo catalog. Every row is clearly DEMO_PRODUCT — names, brands,
 * prices, and images are invented for development and must never be shown
 * to a user as if they were real, purchasable products.
 */
export interface DemoProductSeed {
  name: string;
  category: string;
  subcategory: string;
  brand: string;
  price: number;
  previousPrice: number | null;
  image: string;
  store: string;
  description: string;
  colors: string[];
  sizes: string[];
  material: string;
  style: string[];
  gender: Gender;
  rating: number;
  reviewCount: number;
  tags: string[];
}

function img(seed: string) {
  return `https://picsum.photos/seed/${seed}/600/800`;
}

export const demoProducts: DemoProductSeed[] = [
  // ── Masculino — camisas / tops ─────────────────────────────
  {
    name: "Camisa Linho Essencial",
    category: "top",
    subcategory: "camisa",
    brand: "Studio Norte",
    price: 189,
    previousPrice: 229,
    image: img("camisa-linho-essencial"),
    store: "Loja Demo",
    description: "Camisa de linho leve, caimento reto, ideal para clima quente.",
    colors: ["branco", "areia"],
    sizes: ["P", "M", "G", "GG"],
    material: "linho",
    style: ["casual", "smart casual"],
    gender: "male",
    rating: 4.6,
    reviewCount: 128,
    tags: ["verão", "viagem", "leve"],
  },
  {
    name: "Camisa Social Slim Microlistrada",
    category: "top",
    subcategory: "camisa",
    brand: "Aldeia",
    price: 249,
    previousPrice: null,
    image: img("camisa-social-slim"),
    store: "Loja Demo",
    description: "Camisa social de algodão com corte slim e listras discretas.",
    colors: ["azul claro", "branco"],
    sizes: ["P", "M", "G"],
    material: "algodão",
    style: ["elegante", "formal"],
    gender: "male",
    rating: 4.7,
    reviewCount: 94,
    tags: ["trabalho", "jantar", "casamento"],
  },
  {
    name: "Camiseta Básica Premium",
    category: "top",
    subcategory: "camiseta",
    brand: "Base Co.",
    price: 79,
    previousPrice: 99,
    image: img("camiseta-basica-premium"),
    store: "Loja Demo",
    description: "Camiseta de algodão pima, corte reto, gola careca.",
    colors: ["preto", "branco", "cinza"],
    sizes: ["P", "M", "G", "GG"],
    material: "algodão pima",
    style: ["casual", "streetwear", "minimalista"],
    gender: "male",
    rating: 4.5,
    reviewCount: 341,
    tags: ["básico", "dia a dia"],
  },
  {
    name: "Camiseta Oversized Gráfica",
    category: "top",
    subcategory: "camiseta",
    brand: "Volt",
    price: 99,
    previousPrice: null,
    image: img("camiseta-oversized-grafica"),
    store: "Loja Demo",
    description: "Camiseta oversized com estampa gráfica minimalista nas costas.",
    colors: ["preto", "off-white"],
    sizes: ["M", "G", "GG"],
    material: "algodão",
    style: ["streetwear", "casual"],
    gender: "male",
    rating: 4.4,
    reviewCount: 156,
    tags: ["streetwear", "urbano"],
  },
  {
    name: "Polo Piquet Clássica",
    category: "top",
    subcategory: "polo",
    brand: "Aldeia",
    price: 139,
    previousPrice: null,
    image: img("polo-piquet-classica"),
    store: "Loja Demo",
    description: "Polo de piquet com acabamento premium, corte moderno.",
    colors: ["verde musgo", "marinho", "branco"],
    sizes: ["P", "M", "G", "GG"],
    material: "piquet",
    style: ["smart casual", "casual"],
    gender: "male",
    rating: 4.5,
    reviewCount: 87,
    tags: ["fim de semana", "viagem"],
  },
  {
    name: "Suéter Tricô Meia Malha",
    category: "top",
    subcategory: "suéter",
    brand: "Studio Norte",
    price: 219,
    previousPrice: 259,
    image: img("sueter-trico-meia-malha"),
    store: "Loja Demo",
    description: "Suéter de tricô fino, gola redonda, cai bem sobre camisa.",
    colors: ["grafite", "camel"],
    sizes: ["P", "M", "G"],
    material: "lã mesclada",
    style: ["smart casual", "elegante"],
    gender: "male",
    rating: 4.6,
    reviewCount: 63,
    tags: ["outono", "jantar"],
  },

  // ── Masculino — calças / bottoms ────────────────────────────
  {
    name: "Calça Chino Slim",
    category: "bottom",
    subcategory: "calça chino",
    brand: "Aldeia",
    price: 199,
    previousPrice: null,
    image: img("calca-chino-slim"),
    store: "Loja Demo",
    description: "Calça chino de sarja leve, corte slim, elástico discreto na cintura.",
    colors: ["bege", "grafite", "verde militar"],
    sizes: ["38", "40", "42", "44"],
    material: "sarja",
    style: ["smart casual", "casual"],
    gender: "male",
    rating: 4.6,
    reviewCount: 210,
    tags: ["trabalho", "viagem"],
  },
  {
    name: "Calça Jeans Reta Escura",
    category: "bottom",
    subcategory: "calça jeans",
    brand: "Volt Denim",
    price: 229,
    previousPrice: 269,
    image: img("calca-jeans-reta-escura"),
    store: "Loja Demo",
    description: "Jeans de lavagem escura, corte reto, tecido com leve elastano.",
    colors: ["azul escuro"],
    sizes: ["38", "40", "42", "44"],
    material: "denim",
    style: ["casual", "streetwear"],
    gender: "male",
    rating: 4.5,
    reviewCount: 189,
    tags: ["dia a dia", "básico"],
  },
  {
    name: "Calça Social Alfaiataria",
    category: "bottom",
    subcategory: "calça social",
    brand: "Studio Norte",
    price: 269,
    previousPrice: null,
    image: img("calca-social-alfaiataria"),
    store: "Loja Demo",
    description: "Calça de alfaiataria com caimento reto e tecido com leve stretch.",
    colors: ["preto", "grafite", "azul marinho"],
    sizes: ["38", "40", "42", "44"],
    material: "poliéster/lã",
    style: ["elegante", "formal"],
    gender: "male",
    rating: 4.7,
    reviewCount: 71,
    tags: ["casamento", "trabalho"],
  },
  {
    name: "Bermuda Sarja Utilitária",
    category: "bottom",
    subcategory: "bermuda",
    brand: "Volt",
    price: 129,
    previousPrice: null,
    image: img("bermuda-sarja-utilitaria"),
    store: "Loja Demo",
    description: "Bermuda de sarja com bolsos utilitários, acima do joelho.",
    colors: ["bege", "verde militar"],
    sizes: ["P", "M", "G", "GG"],
    material: "sarja",
    style: ["casual", "streetwear"],
    gender: "male",
    rating: 4.3,
    reviewCount: 58,
    tags: ["verão", "praia"],
  },

  // ── Masculino — outerwear ───────────────────────────────────
  {
    name: "Blazer Slim Constructed",
    category: "outerwear",
    subcategory: "blazer",
    brand: "Studio Norte",
    price: 549,
    previousPrice: 649,
    image: img("blazer-slim-constructed"),
    store: "Loja Demo",
    description: "Blazer estruturado de corte slim, forro leve, botão duplo.",
    colors: ["grafite", "azul marinho"],
    sizes: ["P", "M", "G", "GG"],
    material: "lã fria",
    style: ["elegante", "formal"],
    gender: "male",
    rating: 4.8,
    reviewCount: 45,
    tags: ["casamento", "jantar", "trabalho"],
  },
  {
    name: "Jaqueta Corta-Vento Técnica",
    category: "outerwear",
    subcategory: "jaqueta",
    brand: "Volt",
    price: 299,
    previousPrice: null,
    image: img("jaqueta-corta-vento"),
    store: "Loja Demo",
    description: "Jaqueta leve corta-vento com capuz destacável, dobra na bolsa própria.",
    colors: ["preto", "grafite"],
    sizes: ["P", "M", "G", "GG"],
    material: "nylon técnico",
    style: ["streetwear", "casual", "esportivo"],
    gender: "male",
    rating: 4.5,
    reviewCount: 132,
    tags: ["viagem", "outono"],
  },
  {
    name: "Jaqueta Jeans Clássica",
    category: "outerwear",
    subcategory: "jaqueta",
    brand: "Volt Denim",
    price: 259,
    previousPrice: null,
    image: img("jaqueta-jeans-classica"),
    store: "Loja Demo",
    description: "Jaqueta jeans de lavagem média, corte reto atemporal.",
    colors: ["azul médio"],
    sizes: ["P", "M", "G"],
    material: "denim",
    style: ["casual", "streetwear"],
    gender: "male",
    rating: 4.4,
    reviewCount: 76,
    tags: ["fim de semana"],
  },

  // ── Masculino — calçados ────────────────────────────────────
  {
    name: "Tênis Casual Couro Legítimo",
    category: "footwear",
    subcategory: "tênis",
    brand: "Aldeia",
    price: 349,
    previousPrice: 399,
    image: img("tenis-casual-couro"),
    store: "Loja Demo",
    description: "Tênis de couro legítimo, sola de borracha, visual minimalista.",
    colors: ["branco", "off-white"],
    sizes: ["39", "40", "41", "42", "43"],
    material: "couro",
    style: ["smart casual", "casual", "minimalista"],
    gender: "male",
    rating: 4.7,
    reviewCount: 203,
    tags: ["curinga", "viagem"],
  },
  {
    name: "Sapato Social Derby",
    category: "footwear",
    subcategory: "sapato social",
    brand: "Studio Norte",
    price: 429,
    previousPrice: null,
    image: img("sapato-social-derby"),
    store: "Loja Demo",
    description: "Derby de couro com sola de couro costurada, acabamento polido.",
    colors: ["preto", "marrom"],
    sizes: ["39", "40", "41", "42", "43"],
    material: "couro",
    style: ["elegante", "formal"],
    gender: "male",
    rating: 4.6,
    reviewCount: 51,
    tags: ["casamento", "trabalho"],
  },
  {
    name: "Tênis Chunky Streetwear",
    category: "footwear",
    subcategory: "tênis",
    brand: "Volt",
    price: 389,
    previousPrice: null,
    image: img("tenis-chunky-streetwear"),
    store: "Loja Demo",
    description: "Tênis chunky com solado exagerado e mix de materiais.",
    colors: ["preto", "cinza"],
    sizes: ["39", "40", "41", "42", "43"],
    material: "mesh/couro sintético",
    style: ["streetwear"],
    gender: "male",
    rating: 4.3,
    reviewCount: 97,
    tags: ["urbano"],
  },

  // ── Feminino — tops / vestidos ──────────────────────────────
  {
    name: "Blusa Alfaiataria Manga Longa",
    category: "top",
    subcategory: "blusa",
    brand: "Aria",
    price: 179,
    previousPrice: 219,
    image: img("blusa-alfaiataria-manga-longa"),
    store: "Loja Demo",
    description: "Blusa de tecido leve com caimento fluido e botões frontais.",
    colors: ["branco", "preto", "nude"],
    sizes: ["P", "M", "G"],
    material: "viscose",
    style: ["elegante", "smart casual"],
    gender: "female",
    rating: 4.6,
    reviewCount: 118,
    tags: ["trabalho", "jantar"],
  },
  {
    name: "Camiseta Básica Canelada",
    category: "top",
    subcategory: "camiseta",
    brand: "Base Co.",
    price: 69,
    previousPrice: null,
    image: img("camiseta-basica-canelada-fem"),
    store: "Loja Demo",
    description: "Camiseta canelada de caimento justo, gola careca.",
    colors: ["preto", "branco", "terracota"],
    sizes: ["P", "M", "G"],
    material: "algodão canelado",
    style: ["casual", "minimalista"],
    gender: "female",
    rating: 4.5,
    reviewCount: 267,
    tags: ["básico", "dia a dia"],
  },
  {
    name: "Vestido Midi Fluido",
    category: "dress",
    subcategory: "vestido midi",
    brand: "Aria",
    price: 289,
    previousPrice: 329,
    image: img("vestido-midi-fluido"),
    store: "Loja Demo",
    description: "Vestido midi de tecido fluido com fenda discreta, ideal para eventos.",
    colors: ["verde esmeralda", "preto", "vinho"],
    sizes: ["P", "M", "G"],
    material: "crepe",
    style: ["elegante"],
    gender: "female",
    rating: 4.8,
    reviewCount: 84,
    tags: ["casamento", "jantar", "festa"],
  },
  {
    name: "Vestido Curto Amarração",
    category: "dress",
    subcategory: "vestido curto",
    brand: "Aria",
    price: 199,
    previousPrice: null,
    image: img("vestido-curto-amarracao"),
    store: "Loja Demo",
    description: "Vestido curto com amarração lateral e caimento leve.",
    colors: ["azul serenity", "preto"],
    sizes: ["P", "M", "G"],
    material: "viscolinho",
    style: ["casual", "smart casual"],
    gender: "female",
    rating: 4.5,
    reviewCount: 143,
    tags: ["primeiro encontro", "verão"],
  },
  {
    name: "Cropped Tricô Canelado",
    category: "top",
    subcategory: "cropped",
    brand: "Volt",
    price: 99,
    previousPrice: null,
    image: img("cropped-trico-canelado"),
    store: "Loja Demo",
    description: "Cropped de tricô canelado, alcinhas ajustáveis.",
    colors: ["preto", "off-white", "lilás"],
    sizes: ["P", "M", "G"],
    material: "tricô",
    style: ["streetwear", "casual"],
    gender: "female",
    rating: 4.4,
    reviewCount: 176,
    tags: ["balada", "verão"],
  },

  // ── Feminino — bottoms ──────────────────────────────────────
  {
    name: "Calça Alfaiataria Pantalona",
    category: "bottom",
    subcategory: "calça social",
    brand: "Aria",
    price: 249,
    previousPrice: null,
    image: img("calca-alfaiataria-pantalona"),
    store: "Loja Demo",
    description: "Calça pantalona de alfaiataria com cintura alta e caimento reto.",
    colors: ["preto", "grafite", "areia"],
    sizes: ["P", "M", "G"],
    material: "poliéster",
    style: ["elegante", "smart casual"],
    gender: "female",
    rating: 4.6,
    reviewCount: 92,
    tags: ["trabalho", "jantar"],
  },
  {
    name: "Calça Jeans Reta Cintura Alta",
    category: "bottom",
    subcategory: "calça jeans",
    brand: "Volt Denim",
    price: 219,
    previousPrice: 259,
    image: img("calca-jeans-reta-cintura-alta"),
    store: "Loja Demo",
    description: "Jeans de cintura alta, corte reto, lavagem clara.",
    colors: ["azul claro"],
    sizes: ["36", "38", "40", "42"],
    material: "denim",
    style: ["casual", "streetwear"],
    gender: "female",
    rating: 4.5,
    reviewCount: 231,
    tags: ["dia a dia"],
  },
  {
    name: "Saia Midi Plissada",
    category: "bottom",
    subcategory: "saia",
    brand: "Aria",
    price: 179,
    previousPrice: null,
    image: img("saia-midi-plissada"),
    store: "Loja Demo",
    description: "Saia midi plissada de caimento leve e elástico na cintura.",
    colors: ["camel", "preto"],
    sizes: ["P", "M", "G"],
    material: "poliéster plissado",
    style: ["elegante", "smart casual"],
    gender: "female",
    rating: 4.6,
    reviewCount: 67,
    tags: ["trabalho", "outono"],
  },

  // ── Feminino — outerwear ────────────────────────────────────
  {
    name: "Blazer Alfaiataria Feminino",
    category: "outerwear",
    subcategory: "blazer",
    brand: "Aria",
    price: 379,
    previousPrice: 429,
    image: img("blazer-alfaiataria-feminino"),
    store: "Loja Demo",
    description: "Blazer estruturado de ombro levemente marcado, forro completo.",
    colors: ["preto", "off-white", "xadrez"],
    sizes: ["P", "M", "G"],
    material: "poliéster/viscose",
    style: ["elegante", "formal"],
    gender: "female",
    rating: 4.7,
    reviewCount: 58,
    tags: ["trabalho", "entrevista"],
  },
  {
    name: "Trench Coat Clássico",
    category: "outerwear",
    subcategory: "trench coat",
    brand: "Studio Norte",
    price: 459,
    previousPrice: null,
    image: img("trench-coat-classico"),
    store: "Loja Demo",
    description: "Trench coat de gabardine com cinto, corte reto atemporal.",
    colors: ["areia", "preto"],
    sizes: ["P", "M", "G"],
    material: "gabardine",
    style: ["elegante", "smart casual"],
    gender: "female",
    rating: 4.8,
    reviewCount: 39,
    tags: ["outono", "viagem"],
  },

  // ── Feminino — calçados ─────────────────────────────────────
  {
    name: "Scarpin Salto Bloco",
    category: "footwear",
    subcategory: "scarpin",
    brand: "Aria",
    price: 259,
    previousPrice: null,
    image: img("scarpin-salto-bloco"),
    store: "Loja Demo",
    description: "Scarpin de salto bloco confortável, bico fino.",
    colors: ["preto", "nude"],
    sizes: ["35", "36", "37", "38", "39"],
    material: "verniz sintético",
    style: ["elegante", "formal"],
    gender: "female",
    rating: 4.5,
    reviewCount: 74,
    tags: ["casamento", "festa"],
  },
  {
    name: "Tênis Branco Minimalista",
    category: "footwear",
    subcategory: "tênis",
    brand: "Base Co.",
    price: 299,
    previousPrice: 339,
    image: img("tenis-branco-minimalista-fem"),
    store: "Loja Demo",
    description: "Tênis branco de couro sintético, silhueta clean.",
    colors: ["branco"],
    sizes: ["35", "36", "37", "38", "39"],
    material: "couro sintético",
    style: ["casual", "minimalista", "smart casual"],
    gender: "female",
    rating: 4.7,
    reviewCount: 188,
    tags: ["curinga", "dia a dia"],
  },
  {
    name: "Sandália Salto Tira Fina",
    category: "footwear",
    subcategory: "sandália",
    brand: "Aria",
    price: 189,
    previousPrice: null,
    image: img("sandalia-salto-tira-fina"),
    store: "Loja Demo",
    description: "Sandália de salto médio com tiras finas, fecho lateral.",
    colors: ["preto", "dourado"],
    sizes: ["35", "36", "37", "38", "39"],
    material: "sintético metalizado",
    style: ["elegante", "casual"],
    gender: "female",
    rating: 4.4,
    reviewCount: 61,
    tags: ["festa", "primeiro encontro"],
  },

  // ── Unissex — acessórios e básicos ──────────────────────────
  {
    name: "Tênis Runner Unissex",
    category: "footwear",
    subcategory: "tênis esportivo",
    brand: "Volt",
    price: 329,
    previousPrice: null,
    image: img("tenis-runner-unissex"),
    store: "Loja Demo",
    description: "Tênis leve para corrida ou uso urbano, amortecimento macio.",
    colors: ["preto", "cinza", "branco"],
    sizes: ["37", "38", "39", "40", "41", "42", "43"],
    material: "mesh respirável",
    style: ["esportivo", "casual", "streetwear"],
    gender: "unisex",
    rating: 4.6,
    reviewCount: 214,
    tags: ["esporte", "urbano"],
  },
  {
    name: "Boné Aba Curva Minimal",
    category: "accessory",
    subcategory: "boné",
    brand: "Volt",
    price: 89,
    previousPrice: null,
    image: img("bone-aba-curva-minimal"),
    store: "Loja Demo",
    description: "Boné de sarja com logo bordado discreto, ajuste traseiro.",
    colors: ["preto", "bege"],
    sizes: ["único"],
    material: "sarja",
    style: ["streetwear", "casual"],
    gender: "unisex",
    rating: 4.3,
    reviewCount: 102,
    tags: ["acessório"],
  },
  {
    name: "Cinto de Couro Reversível",
    category: "accessory",
    subcategory: "cinto",
    brand: "Studio Norte",
    price: 119,
    previousPrice: null,
    image: img("cinto-couro-reversivel"),
    store: "Loja Demo",
    description: "Cinto de couro legítimo reversível preto/marrom, fivela discreta.",
    colors: ["preto/marrom"],
    sizes: ["36", "38", "40", "42"],
    material: "couro",
    style: ["elegante", "smart casual", "formal"],
    gender: "unisex",
    rating: 4.5,
    reviewCount: 47,
    tags: ["acessório", "trabalho"],
  },
  {
    name: "Mochila Urbana Slim",
    category: "accessory",
    subcategory: "mochila",
    brand: "Volt",
    price: 229,
    previousPrice: 259,
    image: img("mochila-urbana-slim"),
    store: "Loja Demo",
    description: "Mochila slim com compartimento para notebook, tecido resistente à água.",
    colors: ["preto", "grafite"],
    sizes: ["único"],
    material: "poliéster ripstop",
    style: ["casual", "streetwear", "minimalista"],
    gender: "unisex",
    rating: 4.6,
    reviewCount: 133,
    tags: ["viagem", "trabalho"],
  },
  {
    name: "Bolsa Tiracolo Estruturada",
    category: "accessory",
    subcategory: "bolsa",
    brand: "Aria",
    price: 249,
    previousPrice: null,
    image: img("bolsa-tiracolo-estruturada"),
    store: "Loja Demo",
    description: "Bolsa tiracolo estruturada com alça ajustável e fecho magnético.",
    colors: ["preto", "caramelo"],
    sizes: ["único"],
    material: "couro sintético",
    style: ["elegante", "smart casual"],
    gender: "female",
    rating: 4.6,
    reviewCount: 79,
    tags: ["trabalho", "jantar"],
  },
  {
    name: "Óculos de Sol Redondo",
    category: "accessory",
    subcategory: "óculos",
    brand: "Base Co.",
    price: 149,
    previousPrice: null,
    image: img("oculos-de-sol-redondo"),
    store: "Loja Demo",
    description: "Óculos de sol com armação redonda e proteção UV400.",
    colors: ["preto", "tartaruga"],
    sizes: ["único"],
    material: "acetato",
    style: ["casual", "streetwear", "elegante"],
    gender: "unisex",
    rating: 4.4,
    reviewCount: 91,
    tags: ["verão", "acessório"],
  },
];
